/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */ 
SreOper: [
  
    {
      type: 'autogenerated',
      dirName: 'Sre/1-日常运维',
     // collapsed: false, //控制是否折叠或者打开

  },
], 

SreMiddleSoft: [
    {
        type: 'autogenerated',
        dirName: 'Sre/2-中间件',
        //collapsed: true,   //控制是否折叠或者打开
    },
], 


SreMianshi: [
    {
        type: 'autogenerated',
        dirName: 'Sre/3-面试题',
        //collapsed: true,   //控制是否折叠或者打开
    },
], 


k8s: [
  
    {
      type: 'autogenerated',
      dirName: 'k8s',
     // collapsed: false, //控制是否折叠或者打开
  },
], 

PrometheusGrafana: [
{
    type: 'autogenerated',
    dirName: 'Prometheus/grafana',
   // collapsed: false, //控制是否折叠或者打开
},
], 

PrometheusServer: [
    {
    type: 'autogenerated',
    dirName: 'Prometheus/prometheus',
   // collapsed: false, //控制是否折叠或者打开
},
], 

PrometheusAlert: [
    {
    type: 'autogenerated',
    dirName: 'Prometheus/alertManager',
   // collapsed: false, //控制是否折叠或者打开
},
], 



DevOpsJenkins: [
  
    {
      type: 'autogenerated',
      dirName: 'DevOps/1-jenkins',
     // collapsed: false, //控制是否折叠或者打开
  },
//   {
//     type: 'category',
//     label: '基于ansible发布',
//    // collapsed: false, //控制是否折叠或者打开
//     items: [
//         {
//             type: 'autogenerated',
//             dirName: 'DevOps/1-jenkins/2-通过ansible实现服务发布', // Generate section automatically based on files
//         },
//     ],
// },  
],  

DevOpsGitOps: [
  
    {
      type: 'autogenerated',
      dirName: 'DevOps/2-gitOps',
     // collapsed: false, //控制是否折叠或者打开
  },
],  

DevOpsElk: [
  
    {
      type: 'autogenerated',
      dirName: 'DevOps/3-ELK',
     // collapsed: false, //控制是否折叠或者打开
  },
],  

DevOpsSkywalking: [
  
    {
      type: 'autogenerated',
      dirName: 'DevOps/4-skywalking',
     // collapsed: false, //控制是否折叠或者打开
  },
], 

DevOpsobservability: [
  
    {
      type: 'autogenerated',
      dirName: 'DevOps/5-observability',
     // collapsed: false, //控制是否折叠或者打开
  },
], 

DevOpsterraform: [
    {
      type: 'autogenerated',
      dirName: 'DevOps/6-terraform',
     // collapsed: false, //控制是否折叠或者打开
  },
], 

GoalngJichu: [
  
    {
      type: 'autogenerated',
      dirName: 'Golang/golang基础',
     // collapsed: false, //控制是否折叠或者打开
  },
],  

GoalngJinjie: [
  
    {
      type: 'autogenerated',
      dirName: 'Golang/golang进阶',
     // collapsed: false, //控制是否折叠或者打开
  },
], 

GoalngOper: [
  
    {
      type: 'autogenerated',
      dirName: 'Golang/golang运维',
     // collapsed: false, //控制是否折叠或者打开
  },
], 

GoalngVue: [
  
    {
      type: 'autogenerated',
      dirName: 'Golang/VUE',
     // collapsed: false, //控制是否折叠或者打开
  },
],

JAVA: [
  
    {
      type: 'autogenerated',
      dirName: 'Java/JAVA',
     // collapsed: false, //控制是否折叠或者打开
  },
],


English: [
  
    {
      type: 'autogenerated',
      dirName: 'Treasure/English',
     // collapsed: false, //控制是否折叠或者打开
  },
],

Wisdom: [
  
    {
      type: 'autogenerated',
      dirName: 'Treasure/Wisdom',
     // collapsed: false, //控制是否折叠或者打开
  },
],

Studytour: [
  
    {
      type: 'autogenerated',
      dirName: 'Treasure/Studytour',
     // collapsed: false, //控制是否折叠或者打开
  },
],



};

module.exports = sidebars;
