/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "LiteShell",
  "tagline": "Dinosaurs are cool",
  "favicon": "img/favicon.ico",
  "url": "https://book.onlinebookshell.co.in",
  "baseUrl": "/",
  "organizationName": "shouji1128955",
  "projectName": "bookshell",
  "trailingSlash": false,
  "onBrokenLinks": "throw",
  "onBrokenMarkdownLinks": "warn",
  "themes": [
    [
      "/Users/zhanglaiqiang/Mywork/shouji1128955/shouji1128955.github.io/node_modules/@easyops-cn/docusaurus-search-local/dist/server/server/index.js",
      {
        "hashed": true,
        "language": [
          "en",
          "zh"
        ]
      }
    ]
  ],
  "i18n": {
    "defaultLocale": "zh-CN",
    "locales": [
      "zh-CN",
      "en"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "presets": [
    [
      "@docusaurus/preset-classic",
      {
        "docs": {
          "sidebarCollapsed": true,
          "sidebarPath": "/Users/zhanglaiqiang/Mywork/shouji1128955/shouji1128955.github.io/sidebars.js",
          "editUrl": "https://github.com/shouji1128955/bookshell/edit/main",
          "showLastUpdateAuthor": true,
          "showLastUpdateTime": true
        },
        "blog": {
          "showReadingTime": true,
          "editUrl": "https://github.com/shouji1128955/bookshell/tree/main/blog"
        },
        "theme": {
          "customCss": "/Users/zhanglaiqiang/Mywork/shouji1128955/shouji1128955.github.io/src/css/custom.css"
        }
      }
    ]
  ],
  "themeConfig": {
    "docs": {
      "sidebar": {
        "hideable": true,
        "autoCollapseCategories": true
      },
      "versionPersistence": "localStorage"
    },
    "image": "https://docusaurus.io/zh-CN/img/undraw_typewriter.svg",
    "navbar": {
      "title": "LiteShell",
      "logo": {
        "alt": "LiteShell",
        "src": "img/logo.svg"
      },
      "items": [
        {
          "label": "Sre",
          "position": "left",
          "items": [
            {
              "type": "docSidebar",
              "sidebarId": "SreOper",
              "to": "/docs/Sre/1-日常运维",
              "label": "日常运维"
            },
            {
              "type": "docSidebar",
              "sidebarId": "SreMiddleSoft",
              "to": "/docs/Sre/2-中间件",
              "label": "中间件"
            },
            {
              "type": "docSidebar",
              "sidebarId": "SreMianshi",
              "to": "/docs/Sre/3-面试题",
              "label": "面试题"
            }
          ]
        },
        {
          "label": "Kubernetes",
          "position": "left",
          "items": [
            {
              "type": "docSidebar",
              "sidebarId": "k8s",
              "to": "/docs/k8s",
              "label": "Kubernetes"
            }
          ]
        },
        {
          "label": "Prometheus",
          "position": "left",
          "items": [
            {
              "type": "docSidebar",
              "sidebarId": "PrometheusGrafana",
              "to": "/docs/Prometheus/grafana",
              "label": "grafana"
            },
            {
              "type": "docSidebar",
              "sidebarId": "PrometheusServer",
              "to": "/docs/Prometheus/prometheus",
              "label": "Prometheus"
            },
            {
              "type": "docSidebar",
              "sidebarId": "PrometheusAlert",
              "to": "/docs/Prometheus/alertManager",
              "label": "AlertManager"
            }
          ]
        },
        {
          "label": "DevOps",
          "position": "left",
          "items": [
            {
              "type": "docSidebar",
              "sidebarId": "DevOpsJenkins",
              "to": "/docs/DevOps/1-jenkins",
              "label": "jenkins"
            },
            {
              "type": "docSidebar",
              "sidebarId": "DevOpsGitOps",
              "to": "/docs/DevOps/2-gitOps",
              "label": "gitOps"
            },
            {
              "type": "docSidebar",
              "sidebarId": "DevOpsElk",
              "to": "/docs/DevOps/3-ELK",
              "label": "ELK"
            },
            {
              "type": "docSidebar",
              "sidebarId": "DevOpsSkywalking",
              "to": "/docs/DevOps/4-skywalking",
              "label": "skywalking"
            },
            {
              "type": "docSidebar",
              "sidebarId": "DevOpsobservability",
              "to": "/docs/DevOps/5-observability",
              "label": "observability"
            },
            {
              "type": "docSidebar",
              "sidebarId": "DevOpsterraform",
              "to": "/docs/DevOps/6-terraform",
              "label": "terraform"
            }
          ]
        },
        {
          "label": "Golang",
          "position": "left",
          "items": [
            {
              "type": "docSidebar",
              "sidebarId": "GoalngJichu",
              "to": "/docs/Golang/golang基础",
              "label": "golang基础"
            },
            {
              "type": "docSidebar",
              "sidebarId": "GoalngJinjie",
              "to": "/docs/Golang/golang进阶",
              "label": "golang进阶"
            },
            {
              "type": "docSidebar",
              "sidebarId": "GoalngOper",
              "to": "/docs/Golang/golang运维",
              "label": "golang运维"
            },
            {
              "type": "docSidebar",
              "sidebarId": "GoalngVue",
              "to": "/docs/Golang/VUE",
              "label": "Vue"
            }
          ]
        },
        {
          "label": "JAVA",
          "position": "left",
          "items": [
            {
              "type": "docSidebar",
              "sidebarId": "JAVA",
              "to": "/docs/Java/JAVA",
              "label": "Java"
            }
          ]
        },
        {
          "label": "Treasure",
          "position": "left",
          "items": [
            {
              "type": "docSidebar",
              "sidebarId": "Wisdom",
              "to": "/docs/Treasure/Wisdom",
              "label": "Plan and strategize"
            },
            {
              "type": "docSidebar",
              "sidebarId": "Studytour",
              "to": "/docs/Treasure/Studytour",
              "label": "read book"
            }
          ]
        },
        {
          "to": "/blog",
          "label": "Blog",
          "position": "left"
        },
        {
          "href": "https://github.com/facebook/docusaurus",
          "label": "GitHub",
          "position": "right"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "Docs",
          "items": [
            {
              "label": "LiteShell",
              "href": "https://shouji1128955.github.io"
            }
          ]
        },
        {
          "title": "Community",
          "items": [
            {
              "label": "kubernetes",
              "href": "https://kubernetes.io/"
            },
            {
              "label": "Twitter",
              "href": "https://twitter.com/docusaurus"
            }
          ]
        },
        {
          "title": "More",
          "items": [
            {
              "label": "mindoc",
              "href": "https://mindoc.zlqit.com"
            },
            {
              "label": "GitHub",
              "href": "https://github.com/shouji1128955"
            }
          ]
        }
      ],
      "copyright": "Copyright © 2024 My Blog Project - LiteShell"
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "additionalLanguages": [],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "magicComments": [
      {
        "className": "theme-code-block-highlighted-line",
        "line": "highlight-next-line",
        "block": {
          "start": "highlight-start",
          "end": "highlight-end"
        }
      },
      {
        "className": "code-block-error-line",
        "line": "highlight-next-line-error"
      }
    ],
    "defaultLanguage": "shell",
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": false
    },
    "blog": {
      "sidebar": {
        "groupByYear": true
      }
    },
    "metadata": [],
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "baseUrlIssueBanner": true,
  "future": {
    "experimental_storage": {
      "type": "localStorage",
      "namespace": false
    },
    "experimental_router": "browser"
  },
  "onBrokenAnchors": "warn",
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "plugins": [],
  "scripts": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "format": "mdx",
    "mermaid": false,
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    },
    "anchors": {
      "maintainCase": false
    }
  }
};
