name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
    # Review gh actions docs if you want to further define triggers, paths, etc
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on

permissions:
  contents: write
  pages: write

jobs:
  build:
    name: Build Docusaurus
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build website
        run: yarn build

      #定义构建输出目录
      - name: Upload Build Artifact 
        uses: actions/upload-pages-artifact@v3
        with:
          path: build	

      - name: Create CNAME file
        run: echo 'book.onlinebookshell.co.in' > ./build/CNAME          

  deploy:
    name: Deploy to GitHub Pages
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source
      pages: write
      

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # 使用 GitHub 提供的 token
          publish_dir: ./build # 指定要发布的构建输出目录
          user_name: github-actions[bot]
          user_email: 409003604@qq.com # 提交时使用的用户邮箱
      - name: Notify Deployment
        run: |
          echo "Deployed to environment: ${{ job.environment.name }}"
          echo "Access your site at: ${{ job.environment.url }}"
